name: TryHackMe Update Badge

on:
  schedule:
    # every 12 hours
    - cron: '0 0/12 * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: Update this repo's tryhackme badge with the latest tryhackme image badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          # Replace with your tryhackme username
          username: "5uch4N00b"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
