name: TryHackMe Update Badge

on:
  schedule:
    # Every 24 hours
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: Update this repo's tryhackme badge with the latest tryhackme image badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          
          username: "C3n7ral051nt4g3ncy"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
