name: TryHackMe Update Badge

on:
  schedule:
    # I have set this to run every 6 hours for my README.md https://github.com/C3n7ral051nt4g3ncy/
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: Update this repo's tryhackme badge with the latest tryhackme image badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          
          username: "5uch4N00>"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          # A big thanks to p4p1 for this nice workflow :-)
